### ISSUE TITLE
Multiple Line Display

### ISSUE THREAD

**Issue by AmandaBarton** [MurhafSousli/ngx-bar-rating#10]
Is there a way to display the star ratings on multiple lines?

For example, if I have a rating system out of 10, is there a way to display the bar as 2 rows of 5?

**Comment by MurhafSousli** [comment]
Hi @AmandaBarton Yes you can do this with css. copy the following in your global style

```css
.br-{theme-name} .br-units {
  flex-wrap: wrap !important;
  justify-content: center;
}
.br-{theme-name} .br-unit { 
  flex: 0 1 18%;
}
```
```html
<bar-rating name="rating" [(rate)]="userRate" [theme]="'horizontal'" [max]="10"
[showText]="true" [titles]="['Bad', 'Mediocre' , 'Good', 'Awesome']">></bar-rating>
```
replace `{theme-name}` with the name of the theme you are using, here is a [plunker](https://plnkr.co/edit/3v6yQwfjRHh6gXXMlqOp?p=preview).
