### ISSUE TITLE
--br-font-size is not working on angular

### ISSUE THREAD

**Issue by smimar** [MurhafSousli/ngx-bar-rating#103]
Hi,
I am trying to make the size of the stars smaller but no matter what I do I can't get them smaller than their default size. I am using ionic/angular/capacitor combination. 

.html
 <bar-rating  class="rating" [rate]="rating" [readOnly]="true" [max]="5" [theme]="'stars'"></bar-rating>

.css
.rating{
style="--br-font-size:10px;"
}

**Comment by MurhafSousli** [comment]
You are using the `stars` theme which is based on a star image, font-size won't help with this theme! instead change the height and the width like the following:

```scss
.rating {
  ::ng-deep {
    .br-unit-inner {
      width: 10px;
      height: 10px;
    }
  }
}
```

If you want to change the star that changes with the font size, use the default theme, like in this [stackblitz](https://stackblitz.com/edit/ngx-bar-rating?file=src%2Fstyles.scss,src%2Fapp%2Fapp.component.css)
