### ISSUE TITLE
readonly attribute is not working in the version 7.0.0

### ISSUE THREAD

**Issue by nnitish** [MurhafSousli/ngx-bar-rating#111]
[readonly]='true' is not working in version 7.0.0 but it is working perfectly in the lower version.
Verified version 6.0.0, working as expected.

**Comment by MurhafSousli** [comment]
A quick workaround now is by adding the following your global styles

```css
.br-readonly .br-unit {
  pointer-events: none;
}
```
