### ISSUE TITLE
How to select and show float rating?

### ISSUE THREAD

**Issue by lakhvir1994** [MurhafSousli/ngx-bar-rating#9]
I am working on a rating section where I want ratings out of five. I want float values to be select from stars and show half star for 0.5. 
Is it possible with this plug in, If it is possible then tell me the solution.

**Comment by MurhafSousli** [comment]
The component support half star out of the box, but the only predefined theme that shows the half star is `fontawesome-o`.

```html
<bar-rating [rate]="faoRating" (rateChange)="onFaoRate($event)" [max]="10" [theme]="'fontawesome-o'"></bar-rating>
```

Ofcourse, you can define your own theme

```scss
.br-custom-theme {

  .br-unit {
    align-items: center;
  }

  .br-unit {
    background-color: $color0;
    margin-right: 2px;
  }

  .br-selected {
    background-color: $color1;
  }

  .br-active {
    background-color: $color2;
  }

  .br-fraction {
    background-color: $color3;
  }

}
```
```ts
<bar-rating [rate]="faoRating" (rateChange)="onFaoRate($event)" [max]="10" [theme]="'custom-theme'"></bar-rating>
```
